# Generated by Django 5.0 on 2025-10-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
    ]
