# Generated by Django 5.0 on 2025-10-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_invoice_quotation_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='breadth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='srno',
            field=models.IntegerField(default=0),
        ),
    ]
