# Generated by Django 5.0 on 2025-10-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_invoiceitem_breadth_invoiceitem_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
