# Generated by Django 5.0 on 2025-10-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_alter_invoiceitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(),
        ),
    ]
