# Generated by Django 5.2 on 2025-10-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0008_invoiceitem_area_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='terms_and_conditions',
            new_name='note',
        ),
    ]
