# Generated by Django 5.2 on 2025-10-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0009_rename_terms_to_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Invoice')], default='quotation', max_length=20),
        ),
    ]
